[package]
name = "statistical"
version = "0.1.0"
authors = ["Jamie Blondin <jblondin@gmail.com>"]

[dependencies]
error-chain = "*"
matrix = { git = "https://github.com/jblondin/matrix" }
etl = { git = "https://github.com/jblondin/etl" }
unittest = { git = "https://github.com/jblondin/unittest" }
